#!/usr/bin/env sh
if [ "${DEBUG}" = "true" ]; then
  set -x
fi

exact_match=$(git describe --exact-match --dirty 2>/dev/null)
retval=$?
if [ $retval -gt 0 ]; then
  git describe --dirty --long
else
  echo "${exact_match}"
fi
