name: Go
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        check-latest: true
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: Print theo-agent -version
      run: ./build/theo-agent -version
