name: Go

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check version
        run: DEBUG=true ./ci/version
      - name: Test
        run: make test
      - name: Build
        run: make build
      - name: Print theo-agent -version
        run: ./build/theo-agent -version
